modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT License"
logoFile= "kotloudron_logo.png"
authors="_BENDY659_"
credits="Small boobs :("

[[mods]]
    modId = "halva_kombat"
    version = "${file.jarVersion}"
    displayName = "Kotloudron"
    description = "This special addon for mod 'HollowEngine'."

[[dependencies.halva_kombat]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.6,44.0.0)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.halva_kombat]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.19.3)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.halva_kombat]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3.12.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.halva_kombat]]
    modId="hc"
    mandatory=true
    versionRange="[1.6.2,)"
    ordering = "NONE"
    side = "BOTH"